create schema if not EXISTS EXEMPLOS;

use EXEMPLOS;

CREATE table if not EXISTS exemplos.CARTA (
	ID INTEGER auto_increment NOT NULL,
	NOME varchar(255) NOT NULL,
	FORCA INTEGER NOT NULL,
	INTELIGENCIA INTEGER NOT NULL,
	VELOCIDADE INTEGER NOT NULL,
	DATA_CADASTRO DATE NOT NULL,
	CONSTRAINT CARTA_pk PRIMARY KEY (ID)
);

-- V2: criação da tabela JOGADOR
CREATE table if not EXISTS exemplos.JOGADOR (
	ID INTEGER auto_increment NOT NULL,
	NOME varchar(255) NOT NULL,
	EMAIL varchar(255) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	TOTAL_PARTIDAS INTEGER NOT NULL,
	PERCENTUAL_VITORIAS DOUBLE NOT NULL,
	CONSTRAINT CARTA_pk PRIMARY KEY (ID)
);

-- V3: criação das tabelas PARTIDA e CARTA_PARTIDA
CREATE table if not EXISTS exemplos.PARTIDA (
	ID INTEGER auto_increment NOT NULL,
	ID_JOGADOR INTEGER NOT NULL,
	ROUNDS_VENCIDOS_JOGADOR INTEGER NOT NULL DEFAULT 0,
	ROUNDS_VENCIDOS_CPU INTEGER NOT NULL DEFAULT 0,
	ROUNDS_EMPATADOS INTEGER NOT NULL DEFAULT 0,
	RESULTADO varchar(255),
	DATA DATE NOT NULL,
	FORCA_UTILIZADA BOOLEAN,
	INTELIGENCIA_UTILIZADA BOOLEAN,
	VELOCIDADE_UTILIZADA BOOLEAN,
	CONSTRAINT PARTIDA_PK PRIMARY KEY (ID),
	CONSTRAINT ID_JOGADOR foreign key (ID_JOGADOR) references exemplos.JOGADOR(ID)
);

CREATE table if not EXISTS exemplos.CARTA_PARTIDA (
	ID INTEGER auto_increment NOT NULL,
	ID_PARTIDA INTEGER NOT NULL,
	ID_CARTA INTEGER NOT NULL,
	DO_JOGADOR BOOLEAN,
	UTILIZADA BOOLEAN,
	CONSTRAINT CARTA_PARTIDA_PK PRIMARY KEY (ID),
	CONSTRAINT ID_PARTIDA foreign key (ID_PARTIDA) references exemplos.PARTIDA(ID),
	CONSTRAINT ID_CARTA foreign key (ID_CARTA) references exemplos.CARTA(ID)
);